# .github/actions/setup-dotnet/action.yml
name: 'Generate Jetproger.Kit.Transformings'
description: 'Generate package Jetproger.Kit.Transformings'
runs:
  using: "composite"
  steps:
    - name: Restore Jetproger.Kit.Transformings
      run: dotnet restore "./Jetproger.Kit.Transformings/Jetproger.Kit.Transformings.sln"
      shell: bash
    - name: Build Jetproger.Kit.Transformings
      run: dotnet build -c Release --no-restore './Jetproger.Kit.Transformings/Jetproger.Kit.Transformings.sln"
      shell: bash
    - name: Pack NuGet Package Jetproger.Kit.Transformings
      run: dotnet pack -c Release --no-build "./Jetproger.Kit.Transformings/Jetproger.Kit.Transformings.sln" -o "./.artifacts"
      shell: bash
    - name: Push NuGet Packages
      run: dotnet nuget push "./.artifacts/*.nupkg" --source "./.packages"
      shell: bash