name: CI/CD for Jetproger.Studio

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - uses: ./.github/actions/setup-python
      with:
        workspace-path: ${{ github.workspace }}

    - uses: ./.github/actions/setup-dotnet
      with:
        workspace-path: ${{ github.workspace }}
    - name: Create NuGet repository
      run: dotnet nuget add source ".\.packages" -n JetprogerStudioPackages

    - uses: ./.github/actions/build-transformings
      with:
        workspace-path: ${{ github.workspace }}

    - uses: ./.github/actions/setup-mssql
      with:
        workspace-path: ${{ github.workspace }}

    - name: Run tests
      run: echo "Hello, GitHub Actions!"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: packages-output
        path: .packages/
        include-hidden-files: true
        retention-days: 3