name: CI/CD for Jetproger.Studio

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      
    - uses: ./.github/actions/setup-python
      with:
        workspace-path: ${{ github.workspace }}
      
    - uses: ./.github/actions/setup-dotnet
      with:
        workspace-path: ${{ github.workspace }}

    - name: Restore
      run: dotnet restore .\Jetproger.Kit.Transformings\Jetproger.Kit.Transformings.sln
    - name: Build
      run: dotnet build --no-restore .\Jetproger.Kit.Transformings\Jetproger.Kit.Transformings.sln
      
    - uses: ./.github/actions/setup-mssql
      with:
        workspace-path: ${{ github.workspace }}
        
    - name: Run tests
      run: echo "Hello, GitHub Actions!"